[package]
name = "ic"
version = "4.0.0"
description = "IC management canister interface (aaaaa-aa)"
repository = "https://github.com/caffeinelabs/mops-ic"
keywords = ["ic", "types", "interface", "http"]
license = "MIT"

[dependencies]
core = "2.5.0"

[requirements]
moc = "1.4.0"

[toolchain]
moc = "1.7.0"

[dev-dependencies]
test = "2.1.2"

[moc]
args = ["--default-persistent-actors", "-W=M0223,M0236,M0237"]
